### ISSUE TITLE
error

### ISSUE THREAD

**Issue by macw** [TalkBank/convert-chinese#1]
I installed node and ran npm.  Then executed this command:
$ convert-chinese --source zh-TW --target zh-CN /Users/epc_528-3/clones/childes-data/Frogs/Chinese-Chang/5/*.cha
then I got a series of 24
translate: Error
I am attaching the input folder I used.

--Brian MacWhinney
[5.zip](https://github.com/TalkBank/convert-chinese/files/963324/5.zip)

**Comment by FranklinChen** [comment]
@macw Strange. I took one of the examples, `061.cha`, and by gradually deleting stuff from the end, got to a file that worked. I currently suspect some kind of file size limit, but will investigate further. The good file was 1634 bytes in size:

```
$ wc -c test.cha
    1634 test.cha
```

If it's just a file size problem, I can certainly work around it by translating chunks and reassembling.

**Comment by FranklinChen** [comment]
I found the problem: https://github.com/matheuss/google-translate-api/pull/13/files

I will create my own fork of the library to solve it.

**Comment by FranklinChen** [comment]
Fixed.
