### ISSUE TITLE
better test

### ISSUE THREAD

**Issue by macw** [TalkBank/convert-chinese#2]
Here is a better test, using their sample files and one CHAT file.  Theirs work, but the CHAT file gives an error.  Not clear why.

--Brian
[cha.zip](https://github.com/TalkBank/convert-chinese/files/963365/cha.zip)

**Comment by FranklinChen** [comment]
Those are my tiny test files I created, so they work.

I shrank the failing CHAT file to 1599 bytes and it worked.

**Comment by FranklinChen** [comment]
Fixed.
